# Generated by Django 5.2.4 on 2025-07-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeproposal',
            old_name='ad_reciever_id',
            new_name='ad_receiver',
        ),
        migrations.RenameField(
            model_name='exchangeproposal',
            old_name='ad_sender_id',
            new_name='ad_sender',
        ),
    ]
