# Generated by Django 5.2.4 on 2025-07-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_ad_reciever_id_exchangeproposal_ad_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Ожидает'), ('Accepted', 'Принята'), ('Declined', 'Отклонена')], default='Pending', max_length=10),
        ),
    ]
